using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TestClient.SmevTestService;

namespace TestClient
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var client = new SmevTestServiceClient();

            client.Endpoint.Behaviors.Add(new Utils.SmevClientBehavior());

            var header = new HeaderType
                         {
                             MessageClass = MessageClassType.REQUEST,
                             MessageId = Guid.NewGuid().ToString(),
                             TimeStamp = DateTime.Now,
                             NodeId = "00"
                         };

            var message = new MessageType
                          {
                              Date = DateTime.Now,
                              Status = StatusType.REQUEST,
                              Originator = new orgExternalType
                                           {
                                               Code = "FOIV11111",
                                               Name = "Наименование ФОИВ 1"
                                           },
                              Sender = new orgExternalType
                                       {
                                           Code = "FOIV11111",
                                           Name = "Наименование ФОИВ 1"
                                       },
                              Recipient = new orgExternalType
                                          {
                                              Code = "FOIV11111",
                                              Name = "Наименование ФОИВ 2"
                                          },
                              ExchangeType = "2",
                              Item = new ServiceType()
                              {
                                  Mnemonic = "SMEVTESTSERVICE",
                                  Version = "1.00"
                              },
                              TestMsg = "test",
                              CaseNumber = "123",
                              ServiceCode = "12313"
                          };

            var messageData = new MessageDataType
                              {
                                  AppData = new AppDataType(),
                                  AppDocument = new AppDocumentType
                                  {
                                      RequestCode = "req_" + Guid.NewGuid(),
                                      ItemsElementName = new []
                                      {
                                          ItemsChoiceType.BinaryData
                                      },
                                      Items = new object[]
                                      {
                                          Convert.FromBase64String("UEsDBBQABgAIAAAAIQBxDjkrcAEAAKAFAAATANsBW0NvbnRlbnRfVHlwZXNdLnhtbCCi1wEooAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADMlE1OwzAQhfdI3CHyFiVui4QQatoFP0uoBBzA2JPGqmNbHre0t2eS0ApQiFTSBZtEUTTvvflm7Ol8W5lkAwG1szkbZyOWgJVOabvM2evLQ3rNEozCKmGchZztANl8dn42fdl5wISqLeasjNHfcI6yhEpg5jxY+lO4UIlIn2HJvZArsQQ+GY2uuHQ2go1prDXYbPpEAYJWkCxEiI+iIh++NTySGrTPcUZ6LLltC2vvnAnvjZYiUnK+seqHa+qKQktQTq4r8soasYtahf9qiHFnAAdboQ8gFJYAsTJZK7p3voNCrE1M7rdEoIUewOBxrX3CzKiyaR9L7bHHoZ9dP5N3F1Zvzq1OTaWmk1VC233uriWg6S2C88hp1oMDQI1cgUo9SUKIGg7MurxpAevemzEib16TwRm+r8ZBv49BR47Lf5Jj+Kn8Gw8sRQD1HAPdUic/rl+1++Zy2E3pAhw/kP0Zrqs7NpI39+vsAwAA//8DAFBLAwQUAAYACAAAACEAtVUwI/UAAABMAgAACwDOAV9yZWxzLy5yZWxzIKLKASigAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjJLPTsMwDMbvSLxD5PvqbkgIoaW7TEi7IVQewCTuH7WNoyRA9/aEA4JKY9vR9ufPP1ve7uZpVB8cYi9Ow7ooQbEzYnvXanitn1YPoGIiZ2kUxxqOHGFX3d5sX3iklJti1/uosouLGrqU/CNiNB1PFAvx7HKlkTBRymFo0ZMZqGXclOU9hr8eUC081cFqCAd7B6o++jz5src0TW94L+Z9YpdOjECeEzvLduVDZgupz9uomkLLSYMV85zTEcn7ImMDnibaXE/0/7Y4cSJLidBI4PM834pzQOvrgS6faKn4vc484qeE4U1k+GHBxQ9UXwAAAP//AwBQSwMEFAAGAAgAAAAhAN4J/SgCAQAA1AMAABoACAF4bC9fcmVscy93b3JrYm9vay54bWwucmVscyCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyTz2rDMAzG74O9g9F9cZJuZZQ6vYxBr1v3ACZR4tDENpb2J28/k0O6QMkuoReDJPx9P9Cn/eGn78QXBmqdVZAlKQi0pata2yj4OL0+PIMg1rbSnbOoYECCQ3F/t3/DTnP8RKb1JKKKJQWG2e+kpNJgrylxHm2c1C70mmMZGul1edYNyjxNtzL81YBipimOlYJwrDYgToOPzv9ru7puS3xx5WePlq9YyG8XzmQQOYrq0CArmFokx8kmicQgr8PkN4bJl2CyG8NkSzDbNWHI6IDVO4eYQrqsatZegnlaFYaHLoZ+CgyN9ZL945r2HE8JL+5jKcd32oec3WLxCwAA//8DAFBLAwQUAAYACAAAACEAvGFVl2oBAAB7AgAADwAAAHhsL3dvcmtib29rLnhtbIxSy07DMBC8I/EPlu80qfuCqkklBIheEAdozybeNFYdO7Jd0h7hN/gRPqP9I9apGooEEifvenfGM5NMpptSkVewThqd0G4npgR0ZoTUy4Q+P91dXFLiPNeCK6MhoVtwdJqen01qY1cvxqwIEmiX0ML7ahxFLiug5K5jKtA4yY0tucfWLiNXWeDCFQC+VBGL42FUcqnpgWFs/8Nh8lxmcGOydQnaH0gsKO5Rvitk5Wg6yaWC+cER4VX1wEvUvVGUKO78rZAeREL72JoaflzYdXW9lipMB/GIRmlr8tESATlfK/+E9o7smBfrMzYMmyGKuYTafYNCSzYLqYWpwypGu227eEBJ3YwWUvgC51dxr727B7ksfACxURzooxP+JkF8pzmJbuztPnaf+7f9exe/Vgh4hiawtmOJhZ2JbiD5DcBOAFi3APYXoHcCwLoF9BqZR20ZVxmGFo5GChuM2KDZOP436RcAAAD//wMAUEsDBBQABgAIAAAAIQDa6xv/oAYAAIYbAAATAAAAeGwvdGhlbWUvdGhlbWUxLnhtbOxZz24bRRi/I/EOo723thM7jaM6VezYBNq0UewW9Thej3enmd1ZzYyT+lalRyQQoiAuSMCFAwIitYhL+g7uMwSKoEh9Bb6Z2bV34g1J2ggENIfYO/v7/v+Zb8ZXr92PGNolQlIeN7zK5bKHSOzzAY2Dhne717m07CGpcDzAjMek4Y2J9K6tvv3WVbyiQhIRBPSxXMENL1QqWSmVpA/LWF7mCYnh3ZCLCCt4FEFpIPAe8I1YaaFcXipFmMYeinEEbCdfT36cHE4O0K3hkPrEW834txkIiZXUCz4TXc2dZERfPdufHEyeTp5MDp49gO9P4fMjQzvYqWgKOZYtJtAuZg0PRA/4Xo/cVx5iWCp40fDK5s8rrV4t4ZWUiKkTaHN0HfOX0qUEg50FI1ME/anQSqdav7I+5W8ATM3j2u12q12Z8jMA7PtgudUlz7PaWa40M545kP06z7tVrpWrLj7Hf3FO53qz2azVU10sUwOyX6tz+OXyUnVtwcEbkMXX5vDV5lqrteTgDcjil+bwnSv1paqLN6CQ0XhnDq0D2umk3KeQIWcbhfBlgC+XU/gMBdkwzTYtYshjddbci/A9LjpAoAkZVjRGapyQIfYh0Vs46guKtUC8QnDujV3y5dySlo2kL2iiGt57CYaimfF7efjdy8PH6OXhwdH+k6P9n44ePjza/8Hycgg3cBzkCV988/EfXzxAvz/+8sWjT4vxMo//5fsPfn76STEQKmqm0fPPDn59cvD88w9/+/ZRAXxN4H4e3qMRkegm2UPbPALbjGNczUlfnI+iF2LqUOAQeBewbqvQAd4cY1aEaxLXeXcENJMi4Duje46u3VCMFC2QfD2MHOAm56zJRaEDrmtZOQ/3RnFQLFyM8rhtjHeLZLdw7IS2PUqgq2ZJ6fi+FRJHzS2GY4UDEhOF9Du+Q0iBdXcpdfy6SX3BJR8qdJeiJqaFLunRvpNIM6INGkFcxkU2Q6gd32zeQU3OiqxeJ7suEgoCswLle4Q5bnwHjxSOilj2cMTyDr+BVVikZHcs/DyuLRVEOiCMo/aASFlEc0uAvbmgX8fQvwrDvsnGkYsUiu4U8byBOc8j1/lOK8RRUoTt0jjMY9+VO5CiGG1xVQTf5G6F6GeIA45PDPcdSpxwn94IbtPAUWmWIPrNSOhYQuN2+m9E479qxoxCN7Y58KYZN7w12JqKSmLjWAs+CfcvbLzreBRvEcj1+Y3nTd9903e9/3zfPamWz9ptZw0Weq8eHuycbKbm6MxD85Ay1lVjRm5IMzdL2DwGHVjUfMyZkkwPVUkIX9Nm7+ACgQ0NEly9T1XYDXECM3fF00wCmbIOJEq4hLOfWS7krfEwtyt7cqzpM4XtDxKrTT6wy4t6OTs6TNmYLSgw59VM0KJmcFZhi1dSpmD2qwiraKXOLK1iVDOtz5E2NRliOm8aLE69CVMJglkGvLwEp3otGs4qmJGB9rvdkLOwmChcZIhkiAckjZG2ez5GFROkLFfM5QHkTkGM9DnwFK/lpNU129eQdpYg5cVVTxCXRe91opRl8CxKuo6PlSOL88XJYrTX8Oq1hZqHfJw0vCEcc+FrlEDUpR4EMQvgOslXwqb9qcVsqnwWzXpmmFsEFbjJsH6fM9jpA4mQah3L0KaGeZWmAIu1JKv/Qg3celEG2Ex/BS0WlyEZ/jEtwI9uaMlwSHyVD3ZuRfvOPqatlI8UEd1wsIf6bCS2MYRfpyrYM6ASbitMR9APcNWmvW1euc05Lbr8BZfB2XXMkhCn7VaXaFbJFm7qeKqDecqpB7YV6m6MO78ppuQvyJR8Gv/PTNH7CVwfLA50BHy4/BUY6XpteFyokEMXSkLqdwQMEqZ3QLbAdS28hqSCK2jzKciu/rQ1Z3mYsoZToNqmARIU9iMVCkK2oC2Z7DuFWSXduyxLljIyGZVTVyZW7T7ZJayne+CS3ts9FEKqm26StgGDO55/7nNaQf1ADzn5enN6yHTvtTXwd08+tpjBKLcPm4Em8/9UxYJd1dIb8mzvzRuiX8zGrGpWFSAstxXU07J/RRXOudXajjVn8UItUw6iOG8xLE4HogQugZD+B/sfFT6zP2boDbXHt6G3IvgtQjODtIGsvmQHD6QbpF3sw+BkF20yaVbWtenopL2WbdYXPOlO5R5zttbsLPE+p7Onw5krzqnFi3R26mHH13btRFdDZI+XKCwNs4ONCYz5ISz/QxXv34NAr8OV/4gpaZIJfnYSGEbPrqkDKH4r0ZCu/gkAAP//AwBQSwMEFAAGAAgAAAAhALhKSy0TAQAAtwEAABgAAAB4bC93b3Jrc2hlZXRzL3NoZWV0Mi54bWyMUMFKxDAQvQv+Q5i7TVdZlaXtIiyLHgQR9Z5tJ23YJBOSWVf/3rRlF8GLt3l5b17mvWr95az4xJgM+RoWRQkCfUud8X0N72/bq3sQiZXvlCWPNXxjgnVzeVEdKe7TgMgiO/hUw8AcVlKmdkCnUkEBfWY0Rac4w9jLFCKqblpyVl6X5a10yniYHVbxPx6ktWlxQ+3BoefZJKJVnO9PgwkJmqozmRsDiYi6hocFyKaavv0weEy/ZjGm2BHtR+Kpq6EcpfKPdjuleImiQ60Oll/p+IimHzhXtjy7bxSrvB5Uj88q9sYnYVFnTVncgYizfpqZwvS6BLEjZnInNOSCMBdRFjcgNBGfwHjWufLmBwAA//8DAFBLAwQUAAYACAAAACEAuEpLLRMBAAC3AQAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQzLnhtbIxQwUrEMBC9C/5DmLtNV1mVpe0iLIseBBH1nm0nbdgkE5JZV//etGUXwYu3eXlvXua9av3lrPjEmAz5GhZFCQJ9S53xfQ3vb9urexCJle+UJY81fGOCdXN5UR0p7tOAyCI7+FTDwBxWUqZ2QKdSQQF9ZjRFpzjD2MsUIqpuWnJWXpflrXTKeJgdVvE/HqS1aXFD7cGh59kkolWc70+DCQmaqjOZGwOJiLqGhwXIppq+/TB4TL9mMabYEe1H4qmroRyl8o92O6V4iaJDrQ6WX+n4iKYfOFe2PLtvFKu8HlSPzyr2xidhUWdNWdyBiLN+mpnC9LoEsSNmcic05IIwF1EWNyA0EZ/AeNa58uYHAAD//wMAUEsDBBQABgAIAAAAIQBqKQparAAAALwAAAAUAAAAeGwvc2hhcmVkU3RyaW5ncy54bWw0jbENwjAQRXskdrCuBwcKhJDjFEhMAANYyUEsxeeQuyCYgZZBaCjZwWyEKSjf/3p6prqGTl1wYB+phMW8AIVUx8bTqYTDfjdbg2Jx1LguEpZwQ4bKTieGWVR2iUtoRfqN1ly3GBzPY4+Un2McgpOMw0lzP6BruEWU0OllUax0cJ5A1XEkyV1QI/nziNs/W8PeGrHpkZ7pnd6fe3oZLdbo365z3X4BAAD//wMAUEsDBBQABgAIAAAAIQAdIRZbxQEAAIADAAANAAAAeGwvc3R5bGVzLnhtbKSTTYrcMBCF94G5g9B+Rm6TDEmwPYtAQ2AGAtOBbGVLtgX6MVK5aecCWcwdcocss8gdum+Ukuxxd6+yyMYuPVV9eq6Si4eD0WQvfVDOlnRzl1EibeOEsl1Jv+62t+8pCcCt4NpZWdJJBvpQ3bwpAkxaPvdSAkGEDSXtAYaPjIWml4aHOzdIizut84YDLn3HwuAlFyEWGc3yLLtnhitLq6J1FgJp3GgBXSxCVYTvZM81KhvKqqJx2nkCiEcjSbHcyDnjE9eq9iqmtdwoPc1ynup67gP6TKg8exu15HKpNco6H0UWbSyvgCCl9Woqj6ZQqIqBA0hvt7ggS7ybBrRksUMzJuX9I7vzfNrk7y4KWDqwKmrnBU7ksh2zVBVatoBGver6+AY34LN2AM5gIBTvnOUaQ/ZasQT4OY3U+jlO7Vt7xT60xI5ma+CzKCnOPzbhNcQPWcKZNy8i/5I2s/8bSw7tNR+JF7avTK/Hk3gHSnr8efx1ejn9OP45vRx/0xVF6lFpUPYanNqAbHE4tyKLkwBe462OTVpPw44I2fJRw27dLOk5fpJCjebDmvVF7R0kREnP8WOc2OY+TTusv071FwAA//8DAFBLAwQUAAYACAAAACEAFE4l6UABAAALAgAAGAAAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbIxRS0vEMBC+C/6HMHebVlmVpe0iLIseBPF1z7bTNmybKcnsVv+9ky67CF48BOaR75Xkq6+hVwf0wZIrIEtSUOgqqq1rC/h431zdgwpsXG16cljANwZYlZcX+UR+FzpEVsLgQgEd87jUOlQdDiYkNKKTTUN+MCytb3UYPZp6Bg29vk7TWz0Y6+DIsPT/4aCmsRWuqdoP6PhI4rE3LP5DZ8cAZV5b2cVAymNTwEMGusxn2U+LU/hVKzbbN+yxYqwlPaiYaku0ixefZJRGqP6D3cypXryqsTH7nl9pekTbdiwki7Pa2rApc0+TkmhCHkYTHypbZmKyikOxpgQTTR/KNNcHEavkCOYkeyQZTYvPxrfWBdVjI5g0uQPlj5pzzTTO0wWoLTHTcOo6eXQUsTS5AdUQ8amJ0c7fWP4AAAD//wMAUEsDBBQABgAIAAAAIQAXdRmwUQEAAG0CAAARAAgBZG9jUHJvcHMvY29yZS54bWwgogQBKKAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACUktFKwzAYhe8F36Hkvk3TTael7UBlVw4EJ4p3Ifm3FZs0JNFud76KbyGCe4b6RqbtNivzxsvknP/LOT9JxitReC+gTV7KFJEgRB5IVvJcLlJ0N5v4Z8gzlkpOi1JCitZg0Dg7PkqYilmp4UaXCrTNwXiOJE3MVIqW1qoYY8OWIKgJnEM6cV5qQa076gVWlD3RBeAoDE+xAEs5tRQ3QF/tiWiL5GyPVM+6aAGcYShAgLQGk4DgH68FLcyfA63Sc4rcrpXrtI3bZ3PWiXv3yuR7Y1VVQTVoY7j8BD9Mr2/bqn4um10xQFnCWcw0UFvqrH6rN1+v9ab+qN/rzwT3pGaNBTV26jY+z4FfrA/chw7Hbqt0DwD3XLi4q7JT7geXV7MJyqKQRD4hfnQ+C0fxCYnJ6LEJ8Gu+CdtdiG2M/xCHwx5xB8gSfPBBsm8AAAD//wMAUEsDBBQABgAIAAAAIQD68TJppgEAAFYDAAAQAAgBZG9jUHJvcHMvYXBwLnhtbCCiBAEooAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJyTwY7TMBCG70i8Q+T71mkXIVQ5XqEuUAkQldrtfXAmrYVjW/Zs1HKDK4/Ai/AY2zdaJ1G2KSAO+DQz/+jXN2Nb3BxqkzUYona2YNNJzjK0ypXa7gp2t3l79YplkcCWYJzFgh0xshv5/JlYBecxkMaYJQsbC7Yn8nPOo9pjDXGSZJuUyoUaKKVhx11VaYW3Tt3XaInP8vwlxwOhLbG88k+GrHecN/S/pqVTLV/cbo4+AUvx2nujFVCaUn7UKrjoKsreHBQawceiSHRrVPdB01Hmgo9TsVZgcJGMZQUmouDnglgitEtbgQ5RiobmDSpyIYv6a1rbjGWfIWKLU7AGggZLCatt65MuNj5SkA8/H36dvp2+n34Inhr6YheOe8exfiGvu4YUXDa2Bj1IEi4RN5oMxk/VCgL9hfh6TNwx9LyXjNMx4hPsMMHsn2qPPB6v21gC/Q1t4WoP9ii3i/erd0vBh1x80PZLvPMbdwuEw51cFsV6DwHLdI2Dfi6IZbqOYFqTxR7sDsuh50+hfUHb/pvI6WySp9M9nKEm+PlDyEcAAAD//wMAUEsBAi0AFAAGAAgAAAAhAHEOOStwAQAAoAUAABMAAAAAAAAAAAAAAAAAAAAAAFtDb250ZW50X1R5cGVzXS54bWxQSwECLQAUAAYACAAAACEAtVUwI/UAAABMAgAACwAAAAAAAAAAAAAAAAB8AwAAX3JlbHMvLnJlbHNQSwECLQAUAAYACAAAACEA3gn9KAIBAADUAwAAGgAAAAAAAAAAAAAAAABoBgAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAYACAAAACEAvGFVl2oBAAB7AgAADwAAAAAAAAAAAAAAAACqCAAAeGwvd29ya2Jvb2sueG1sUEsBAi0AFAAGAAgAAAAhANrrG/+gBgAAhhsAABMAAAAAAAAAAAAAAAAAQQoAAHhsL3RoZW1lL3RoZW1lMS54bWxQSwECLQAUAAYACAAAACEAuEpLLRMBAAC3AQAAGAAAAAAAAAAAAAAAAAASEQAAeGwvd29ya3NoZWV0cy9zaGVldDIueG1sUEsBAi0AFAAGAAgAAAAhALhKSy0TAQAAtwEAABgAAAAAAAAAAAAAAAAAWxIAAHhsL3dvcmtzaGVldHMvc2hlZXQzLnhtbFBLAQItABQABgAIAAAAIQBqKQparAAAALwAAAAUAAAAAAAAAAAAAAAAAKQTAAB4bC9zaGFyZWRTdHJpbmdzLnhtbFBLAQItABQABgAIAAAAIQAdIRZbxQEAAIADAAANAAAAAAAAAAAAAAAAAIIUAAB4bC9zdHlsZXMueG1sUEsBAi0AFAAGAAgAAAAhABROJelAAQAACwIAABgAAAAAAAAAAAAAAAAAchYAAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbFBLAQItABQABgAIAAAAIQAXdRmwUQEAAG0CAAARAAAAAAAAAAAAAAAAAOgXAABkb2NQcm9wcy9jb3JlLnhtbFBLAQItABQABgAIAAAAIQD68TJppgEAAFYDAAAQAAAAAAAAAAAAAAAAAHAaAABkb2NQcm9wcy9hcHAueG1sUEsFBgAAAAAMAAwADAMAAEwdAAAAAA==")
                                      }
                                  }
                              };

            client.GetData(ref header, ref message, ref messageData);
        }
    }
}
